### ISSUE TITLE
png.h is missing on the first make invocation

### ISSUE THREAD

**Issue by sl0** [Ho-Ro/nanovna-tools#1]
Where did you take png.h from? Any hints in the Readme welcome.
Thaks.

**Comment by Ho-Ro** [comment]
On my Debian (bullseye) it comes from `libpng-dev`. I added this info in the [`README.md`](https://github.com/Ho-Ro/nanovna-tools/blob/main/README.md).
```
dpkg -S /usr/include/png.h
libpng-dev:amd64: /usr/include/png.h
```
